# Generated by Django 2.2.13 on 2020-08-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(blank=True, max_length=3000, null=True)),
                ('star', models.CharField(blank=True, max_length=20, null=True)),
                ('vote', models.CharField(blank=True, max_length=20, null=True)),
                ('recommend', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
